[package]
name = "untitled"
version = "0.1.0"
authors = ["Jhonny Knaak de Vargas <jhonny.vargas@acad.pucrs.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
